all:
  children:
    bastion:
      hosts:
        bastion.example.com:
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/MyJenkinsKey.pem

    private_nodes:
      hosts:
        private-node-1.internal:
          ansible_host: 10.0.1.19
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/MyJenkinsKey.pem
          ansible_ssh_common_args: "-o ProxyJump='ubuntu@bastion.example.com -i ~/Downloads/ivolve-key.pem'"
        private-node-2.internal:
          ansible_host: 10.0.1.171
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/MyJenkinsKey.pem
          ansible_ssh_common_args: "-o ProxyJump='ubuntu@bastion.example.com -i ~/Downloads/ivolve-key.pem'"

